config/routes.rb
require 'gossip'

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'gossip#index'
  get '/team', to: 'team#show'
  get '/contact', to: 'contact#show'
  get '/welcome/:id', to: 'welcome#say_hello'
  resources :gossip
  resources :user

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name,
    presence: true
    validates :zip_code,
    presence: true
    has_many :users
end

app/models/go_tag.rb
class GoTag < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title,
    presence: true,
    length: {in: 3..14}
    validates :content,
    presence: true
    belongs_to :user
    has_many :go_tags
    has_many :tags, through: :go_tags
end

app/models/pm_user.rb
class PmUser < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :pm_users
    has_many :recipients, class_name: "User", through: :pm_users
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :go_tags
    has_many :gossips, through: :go_tags
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name,
    presence: true
    validates :last_name,
    presence: true
    validates :description,
    presence: true
    validates :email,
    presence: true,
    uniqueness: true
    validates :age,
    presence: true
    belongs_to :city
    has_many :gossips
    has_many :sent_messages, class_name: "PrivateMessage"
    has_many :pm_users
    has_many :received_messages, class_name: "PrivateMessage", through: :pm_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def show
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController

  def show
    id = params[:id]
    @gossipfind = Gossip.find(params[:id])
  end

  def index
    @gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
    @gossip = Gossip.create('title' => params[:title], 'content'=> params[:content], 'user_id' => params[:user_id])

   
    if @gossip.save
    redirect_to gossip_path(@gossip.id)
    flash[:notice]= "Post successfully created"
    else 
      flash[:alert] = "Post aborted"
      render 'new'
    end
    # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
    # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
  end

  def edit
    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end

  def destroy
    # Méthode qui récupère le potin concerné et le détruit en base
    # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
  end

end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def show
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    id = params[:id]
    @userfind = User.find(params[:id])
  end
  def index
    @user = User.all
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def say_hello
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contact/show.html.erb
<!--  <h1>Contact#show</h1>
  <p>Find me in app/views/contact/show.html.erb</p>
-->

<h2> Si tu veux nous contacter poulet : </h2>

app/views/gossip/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>The Gossip Project</title>
</head>

<body>

<div class="row justify-content-center">
<% @gossips.each do |t| %>
    <div class="card m-4 col-sm-12 col-md-4 col-lg-3 text-center">
      <div class="card-body">
        <h5 class="card-title">
     Auteur: <%= t.user[:first_name] %><br/><br/>
        <p class="card-text">
     Potin: <%= t.title %><br/><br/>
     <%= link_to "Lien vers le potin", gossip_path(t.id), :class => "btn btn-secondary"%>  </a>
       </h5>
      </div>
    </div>
    <% end %>
  </div>
</div>

</body>
</html>

app/views/gossip/new.html.erb
<html>
    <head>
      <title>The Gossip Project</title>
    </head>
  <body>
    <!-- ... -->
    <div class="card text-center">
    <%= form_tag url_for(action: 'create'), method: "gossip" do %>
      
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      <div class="card-header">
      Balance quelque chose de croustillant
     </div>
     <div class="card-body">

      <%= label_tag 'Title' %> <br />
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Content' %> <br />
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= label_tag 'User' %> <br />
      <%= text_field_tag 'user_id', @gossip.user_id %>
      <br /> <br />

      <%= submit_tag "Create Gossip" %><br /> <br />
    </div>
      <% if flash[:alert] %>
      <div class="alert alert-danger">
      <strong>Attention !</strong> Ton gossip n'a pas été posté.
      </div>
      <% end %>


    <% end %>

    <div class="card-footer text-muted">
    </div>
    </div>
    <!-- ... -->
  </body>
</html>

app/views/gossip/show.html.erb
<html>
<head>
  <title>The Gossip Project</title>
</head>
<body>
      <h4>Voici la page du potin n° <%= params[:id] %>
      </h4>
        <div class="card text-center">
            <div class="card-header">
             Auteur : <%= @gossipfind.user[:first_name] %>
            </div>
        <div class="card-body">
            <h5 class="card-title">Titre : <%= @gossipfind.title %></h5>
            <p class="card-text">Potin : <%= @gossipfind.content %></p>
            <%= link_to "Lien vers l'utilisateur", user_path(@gossipfind.user[:id]), :class => "btn btn-secondary"%>
        </div>
        <div class="card-footer text-muted">
        Créé le : <%= @gossipfind.created_at %>
        </div>

        <% if flash[:notice] %>
        <div class="alert alert-success">
        <strong>Bravo !</strong> Ton gossip a bien été posté.
        </div>
        <% end %>

        </div>



</body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
<title>The Gossip Project</title>
</head>

<body>

<div class="row justify-content-center">
<% @gossips.each do |t| %>
    <div class="card m-4 col-sm-12 col-md-4 col-lg-3 text-center">
      <div class="card-body">
        <h5 class="card-title">
     Auteur: <%= t.user[:first_name] %>
        <p class="card-text">
     Potin: <%= t.title %><br/>
     <%= link_to "Lien vers le potin", gossip_path(t.id), :class => "btn btn-secondary"%>  </a>
       </h5>
      </div>
    </div>
    <% end %>
  </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <title>The Gossip Project</title>
    <link rel="icon" href="https://i.postimg.cc/pV1Qz2nq/GW.jpg" type="image/x-icon">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
    <a class="navbar-brand" href="/">
    <img src="https://i.postimg.cc/Tw6fHCc7/G.png" width="50" height="50" class="d-inline-block align-center" alt="">
    The Gossip Project</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <%= link_to "Home", root_path, :class =>"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Team", team_path, :class =>"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Contact", contact_path, :class =>"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Create Gossip", new_gossip_path, :class =>"nav-link" %>
        </li>
      </ul>
    </div>
  </nav>

  
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/team/show.html.erb
<!--  <h1>Team#show</h1>
  <p>Find me in app/views/team/show.html.erb</p>
-->
</br>
<h2> Que des n° 10 : </h2> </br>

<div class="card-deck">
  <div class="card">
    <img class="card-img-top" src="https://www.pipotronic.com/img/corporate/49.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Chris</h5>
      <p class="card-text">Un visionnaire et acharné du travail, il saura toujours atteindre ses objectifs. Un véritable meneur d'hommes. Notre Didier Deschamps à nous.</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.pipotronic.com/img/corporate/60.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Flo</h5>
      <p class="card-text">Il a le business dans la peau et flaire les bonnes affaires à des kilomètres. AKA Le loup de Wall Street.</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.pipotronic.com/img/corporate/25.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Ugo</h5>
      <p class="card-text">Dynamique et talentueux, il a plus d'un tour dans son sac. Il est la véritable pierre angulaire de The Gossip Project: Inspecteur Gadget</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.pipotronic.com/img/corporate/63.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Mahmood</h5>
      <p class="card-text">Son rôle multi-casquette en fait un élément indispensable du projet. Le McGyver de la start-up nation.</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.pipotronic.com/img/corporate/05.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">David</h5>
      <p class="card-text">Une énergie incroyable doublée d'un sang-froid à toute épreuve, avec lui chaque idée fait mouche: appelez-le Rocky Balboa.</p>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="https://www.pipotronic.com/img/corporate/11.jpg" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">Jonathan</h5>
      <p class="card-text">L'homme sans qui le projet n'aurait jamais vu le jour, il se jette dans l'aventure à bras-le-corps et est toujours prêt à aider ses compagnons: Rambo 2.0</p>
    </div>
  </div>
</div></br>
<h5> Merci à eux !</h5>

app/views/user/show.html.erb
<html>
<head>
  <title>The Gossip Project</title>
</head>
<body>
      <h4>Voici la page de l'utilisateur <%= params[:id] %>      </h4>
      <p1>
      Prénom : <%= @userfind.first_name %><br/>
      Nom : <%= @userfind.last_name %> <br/>
      Description : <%= @userfind.description %> <br/>
      Adresse email : <%= @userfind.email %> <br/>
      Âge : <%= @userfind.age %> <br/>
      Habite à : <%= @userfind.city[:name] %>
      </p1>


</body>
</html>

app/views/welcome/say_hello.html.erb
<!DOCTYPE html>
<html>
<head>
<title>The Gossip Project</title>
</head>

<body>
<h1>  Bienvenue <%= params["id"]%> </h1>
<h3>Ici c'est notre super site de potins, il est chouette, non ? </h3>
</body>
</html>